language: c
sudo: false
dist: trusty

branches:
  except:
  - appveyor
  - circle
  - gh-pages

matrix:
 allow_failures:
  - env: CABALVER=1.24 GHCVER=8.2.1

 include:
  - env: CABALVER=1.24 GHCVER=8.0.1
    compiler: ": #GHC 8.0.1"
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
  - env: CABALVER=1.24 GHCVER=8.2.1
    compiler: ": #GHC 8.2.1"
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.2.1,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}

before_install:
 - . bin/travis_cabal.sh
 - coda_trap coda_before_install

install:
 - coda_trap coda_install

script:
 - coda_trap coda_script

after_script:
 - coda_trap coda_after_script

notifications:
  irc:
    channels:
      - "irc.freenode.org##coda"
    skip_join: true
    template:
      - "\x0313coda\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
